spring:
  jpa:
    properties:
      hibernate:
        ddl-auto: create
        use-new-id-generator-mappings: false
        connection:
          CharSet: UTF-8
          characterEncoding: UTF-8
          useUnicode: true
  datasource:
    url: jdbc:mysql://localhost:3306/library?useUnicode=true&serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: Hv_UoPiol1Gd
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5


logging:
  pattern:
    file: "%d{HH:mm:ss} %-5p [%c] - %m%n"
  level:
    ROOT: warn
    org.springframework: warn
    javax.faces: warn
    org.omnifaces: warn
    org.springframework.security: warn
    org.hibernate: warn
    org.hibernate.type.descriptor.sql: warn
  file:
    name: C:/temp/YummyBookApp.log